version: '3'
services:
  database:
    build:
      context: ./db
      dockerfile: Containerfile
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=c2E6U2VjcmV0I1Bhc3MxMjM=
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - app-network

  app:
    build:
      context: ./app
      dockerfile: Containerfile
    depends_on:
      - database
    ports:
      - "8081:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: 'mssql+pyodbc://sa:c2E6U2VjcmV0I1Bhc3MxMjM=@192.168.66.147:1433/master?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=yes'
      DATABASE_PASSWORD:
    networks:
      - app-network

networks:
  app-network:
    driver: bridge