version: '3'
services:
  k6:
    image: grafana/k6:latest
    container_name: k6-load-test
    volumes:
      - ./load_test.js:/script.js:ro,z
    command: run --out influxdb=http://influxdb:8086/k6 /script.js
    environment:
      - BASE_URL=${BASE_URL:-http://app-route-ks-hybrid-cloud-poc.apps.rosa.r0r7f1m1d7w4r0m.en6d.p3.openshiftapps.com}
    depends_on:
      - influxdb
    networks:
      - k6-net

  influxdb:
    image: influxdb:1.8
    container_name: k6-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    networks:
      - k6-net

  grafana:
    image: grafana/grafana:latest
    container_name: k6-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Sup@erSecretP@ssw03d
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_BASIC_ENABLED=true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:z
      - ./grafana/dashboards:/var/lib/grafana/dashboards:z
    networks:
      - k6-net

networks:
  k6-net:
